apiVersion: v1
kind: ReplicationController
metadata:
  name: spark-master-controller
  labels:
    provider: bwv988
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: bwv988/ds-spark-master
          env:
            # The below seems necessary because of Kubernetes' auto-creation of env. variables.
            - name: SPARK_MASTER_PORT
              value: "7077"
          ports:
            - containerPort: 7077
          resources:
            requests:
              cpu: 100m
