kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
  labels:
    heritage: helm
    provider: spark
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: bwv988/ds-spark-master
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /workdir
              name: ~datascience-sandboxworkdir
    volumes:
      - name: ~datascience-sandboxworkdir
        hostPath:
          path: ~/datascience-sandbox/workdir/
