kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  labels:
    heritage: helm
    provider: spark
spec:
  replicas: ${SPARK_WORKER_REPLICAS}
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - env:
          - name: SPARK_MASTER_URL
            value: spark://spark-master:7077
        - name: spark-worker
          image: bwv988/ds-spark-worker
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /workdir
              name: ~datascience-sandboxworkdir
      volumes:
        - name: ~datascience-sandboxworkdir
          hostPath:
            path: ~/datascience-sandbox/workdir/
        
