kind: Service
apiVersion: v1
metadata:
  name: spark-webui
  labels:
    heritage: helm
    provider: spark
spec:
  ports:
    - port: 8080
      targetPort: 8181
  selector:
    component: spark-master
  type: LoadBalancer
