version: '2'
services:
    zookeeper:
      image: bwv988/zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"

    postgres:
      image: bwv988/postgres-hive
      container_name: postgres
      ports:
        - "5432:5432"

    namenode:
      image: bwv988/hadoop-namenode
      container_name: namenode
      volumes:
        - ~/ds-playground/hadoop/namenode:/hadoop/dfs/name
        - ~/ds-playground/workdir:/workdir
      environment:
        - CLUSTER_NAME=test
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - CORE_CONF_hadoop_http_staticuser_user=root
        - CORE_CONF_hadoop_proxyuser_hue_hosts=*
        - CORE_CONF_hadoop_proxyuser_hue_groups=*
        - HDFS_CONF_dfs_webhdfs_enabled=true
        - HDFS_CONF_dfs_permissions_enabled=false
        - YARN_CONF_yarn_log___aggregation___enable=true
        - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
        - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
        - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
        - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
        - YARN_CONF_yarn_timeline___service_enabled=true
        - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
        - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        - YARN_CONF_yarn_timeline___service_hostname=historyserver
        - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
        - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
        - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031

      ports:
        - "50070:50070"
        - "8020:8020"

    datanode1:
      image: bwv988/hadoop-datanode
      container_name: datanode1
      depends_on:
        - namenode
      volumes:
        - ~/ds-playground/hadoop/datanode1:/hadoop/dfs/data
      environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - CORE_CONF_hadoop_http_staticuser_user=root
        - CORE_CONF_hadoop_proxyuser_hue_hosts=*
        - CORE_CONF_hadoop_proxyuser_hue_groups=*
        - HDFS_CONF_dfs_webhdfs_enabled=true
        - HDFS_CONF_dfs_permissions_enabled=false
        - YARN_CONF_yarn_log___aggregation___enable=true
        - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
        - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
        - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
        - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
        - YARN_CONF_yarn_timeline___service_enabled=true
        - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
        - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        - YARN_CONF_yarn_timeline___service_hostname=historyserver
        - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
        - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
        - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031

    hive:
      image: bwv988/hadoop-hive
      depends_on:
        - zookeeper
        - postgres
        - namenode
        - datanode1
      container_name: hive
      environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - CORE_CONF_hadoop_http_staticuser_user=root
        - CORE_CONF_hadoop_proxyuser_hue_hosts=*
        - CORE_CONF_hadoop_proxyuser_hue_groups=*
        - HDFS_CONF_dfs_webhdfs_enabled=true
        - HDFS_CONF_dfs_permissions_enabled=false
        - YARN_CONF_yarn_log___aggregation___enable=true
        - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
        - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
        - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
        - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
        - YARN_CONF_yarn_timeline___service_enabled=true
        - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
        - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        - YARN_CONF_yarn_timeline___service_hostname=historyserver
        - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
        - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
        - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      ports:
        - "10000:10000"
        - "10002:10002"
      volumes:
        - /opt/hive/lib
        - /usr/share/java

    spark-master:
      image: bwv988/ds-spark-master
      container_name: spark-master
      environment:
        - SPARK_CONF_spark_eventLog_enabled=true
        - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
        - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - CORE_CONF_hadoop_http_staticuser_user=root
        - CORE_CONF_hadoop_proxyuser_hue_hosts=*
        - CORE_CONF_hadoop_proxyuser_hue_groups=*
        - HDFS_CONF_dfs_webhdfs_enabled=true
        - HDFS_CONF_dfs_permissions_enabled=false
        - YARN_CONF_yarn_log___aggregation___enable=true
        - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
        - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
        - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
        - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
        - YARN_CONF_yarn_timeline___service_enabled=true
        - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
        - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        - YARN_CONF_yarn_timeline___service_hostname=historyserver
        - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
        - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
        - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      ports:
        - "8080:8080"
      depends_on:
        - hive
      volumes:
        - ~/ds-playground/workdir/:/workdir
      volumes_from:
        - hive

    spark-worker:
      image: bwv988/ds-spark-worker
      depends_on:
        - spark-master
      environment:
        - SPARK_CONF_spark_eventLog_enabled=true
        - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
        - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
        - SPARK_MASTER_URL=spark://spark-master:7077
        - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
        - CORE_CONF_hadoop_http_staticuser_user=root
        - CORE_CONF_hadoop_proxyuser_hue_hosts=*
        - CORE_CONF_hadoop_proxyuser_hue_groups=*
        - HDFS_CONF_dfs_webhdfs_enabled=true
        - HDFS_CONF_dfs_permissions_enabled=false
        - YARN_CONF_yarn_log___aggregation___enable=true
        - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
        - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
        - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
        - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
        - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
        - YARN_CONF_yarn_timeline___service_enabled=true
        - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
        - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
        - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
        - YARN_CONF_yarn_timeline___service_hostname=historyserver
        - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
        - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
        - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      volumes_from:
        - spark-master

volumes:
    spark-master:
    hive:
